-- CreateTable
CREATE TABLE "Friends" (
    "FriendID" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "UserID1" TEXT NOT NULL,
    "UserID2" TEXT NOT NULL,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "accepted" BOOLEAN NOT NULL DEFAULT false,
    CONSTRAINT "Friends_UserID1_fkey" FOREIGN KEY ("UserID1") REFERENCES "User" ("email") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "Friends_UserID2_fkey" FOREIGN KEY ("UserID2") REFERENCES "User" ("email") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- CreateIndex
CREATE UNIQUE INDEX "Friends_UserID1_UserID2_key" ON "Friends"("UserID1", "UserID2");
